package metrics

import (
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"
)

var (
	ActorTicks = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: "simulator_actor_ticks_total",
		Help: "Total number of ticks executed per actor.",
	}, []string{"actor"})

	ActorErrors = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: "simulator_actor_errors_total",
		Help: "Total number of errors per actor.",
	}, []string{"actor"})

	ActorTickDuration = promauto.NewHistogramVec(prometheus.HistogramOpts{
		Name:    "simulator_actor_tick_duration_seconds",
		Help:    "Tick duration per actor.",
		Buckets: prometheus.DefBuckets,
	}, []string{"actor"})

	OrdersCreated = promauto.NewCounter(prometheus.CounterOpts{
		Name: "simulator_orders_created_total",
		Help: "Total simulated orders created.",
	})

	OrdersProgressed = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: "simulator_orders_progressed_total",
		Help: "Order status transitions performed by simulator.",
	}, []string{"from", "to"})

	ShipmentsProgressed = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: "simulator_shipments_progressed_total",
		Help: "Shipment status transitions performed by simulator.",
	}, []string{"from", "to"})

	StockAdjusted = promauto.NewCounterVec(prometheus.CounterOpts{
		Name: "simulator_stock_adjusted_total",
		Help: "Stock adjustments performed by simulator.",
	}, []string{"kind"})

	NotificationsCreated = promauto.NewCounter(prometheus.CounterOpts{
		Name: "simulator_notifications_created_total",
		Help: "Notifications generated by simulator.",
	})
)
